### ISSUE TITLE
Motivate better our choices

### ISSUE THREAD

**Issue by bast** [coderefinery/mma#22]
For me:

PyBind11
- pros: simplicity, prototyping and testing of C++ code
- cons: only C++11

F2PY
- pros: direct link between Fortran and Python
- cons: restrictive and intrusive

Cython
- pros: very powerful
- cons: complexity

...

**Comment by blindij** [comment]
Are you more python oriented, choose Cython. Are you C++ oriented, choose Pybind11. Do you need to build bindings for another scripting language, choose SWIG, but use CMake to hide complexity in the building process. F2PY and Boost are not so obvious choices. State something like this in the motivation part.

**Comment by bast** [comment]
Good summary! Let us use that in the material.

**Comment by bast** [comment]
I guess this is now done? If yes, can you please close it?

**Comment by blindij** [comment]
Added to 02-overview session
