### ISSUE TITLE
can coloring be added to shell blocks?

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/mma#31]
some shell blocks are difficult to read since they're long and terminal commands are mixed with long output. Some coloring would help, but I'm not sure if it's possible in markdown

**Comment by blindij** [comment]
It does not seem possible to color commands. Probably best is to make shell command listings simpler, by removing or separating output, and also make the promp simpler (comment #30)

**Comment by bast** [comment]
It is possible but requires some work from us on the Jekyll/JS side. A good workaround is indeed to simplify examples. What I would personally like in the longer term is that it is more clear with colors what needs to be typed, what should be just read, and what is output.

**Comment by bast** [comment]
I think the coloring is a good idea, possible, not completely trivial. I am closing this since I believe that this lesson is now better readable since the terminal input/output is massively reduced. But we may introduce coloring later.
