### ISSUE TITLE
paste code into source files in consistent manner

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/mma#34]
sometimes "cat > source.file" is used, but sometimes it's recommended to use one's favorite editor

**Comment by blindij** [comment]
I will replace the cat && editor usage with a git clone of the necessary source code/CMake files.

**Comment by bast** [comment]
The `cat > source` might be very unfamiliar for many. Also if possible I would recommend cloning a repo where things are pre-filled.

**Comment by blindij** [comment]
Change this to cloning the source code from coderefinery/python-ctools-demo.git
