### ISSUE TITLE
problem with pybind11 and cmake

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/mma#35]
on macosx 10.11 I get a cmake error trying to compile with pybind11:
"""
Could not find a package configuration file provided by "pybind11" with any
  of the following names:

    pybind11Config.cmake
    pybind11-config.cmake

  Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
  "pybind11_DIR" to a directory containing one of the above files.  If
  "pybind11" provides a separate development package or SDK, be sure it has
  been installed.
"""

**Comment by blindij** [comment]
Pybind11 included as a submodule in the cloned repo. We also get to show hierarchical CMake.
