### ISSUE TITLE
add alternatives to wget (curl, ...)

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/mma#39]

**Comment by bast** [comment]
Is wget not available somewhere? (just for my info)

**Comment by wikfeldt** [comment]
yes it can be installed (but it's not shipped with osx like curl). 
the following installation instructions for wget could be added:
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install wget --with-libressl

**Comment by Sabryr** [comment]
I will add curl equivalent of wget command  in /_episodes/07-cffi.md

**Comment by bast** [comment]
Great. Thanks! I did not know that wget wasn't standard.

**Comment by bast** [comment]
Thanks but please close issues with commits - then it is more clear which commit closed what and things get cross-referenced.
